/*
Euler Problem #2:


Each new term in the Fibonacci sequence is
generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence
whose values do not exceed four million,
find the sum of the even-valued terms.

*/

function sum_even_fibonacci_numbers()
{
    var a = 1;
    var b = 0;
    var stack = [];
    var result = 0;
    while(b < 4000000)
    {
        b+=a;
        a+=b
        stack.push(a);
        stack.push(b);
    }
    for(i=0;i<stack.length;i++)
    {
        if(stack[i]%2==0)
        {
            result += stack[i]
        }

    }
    return result;

}